// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDztI8Xt-0OS2Mw6_7mGUCmr0JCc1zleTY',
    appId: '1:889421766285:web:ead9671e274efafdc98cc4',
    messagingSenderId: '889421766285',
    projectId: 'practiceinterview-90a8f',
    authDomain: 'practiceinterview-90a8f.firebaseapp.com',
    storageBucket: 'practiceinterview-90a8f.firebasestorage.app',
    measurementId: 'G-E6ZMKVVEJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJzsFIFmdfpvQyplcBnF202FSe2lzV-E',
    appId: '1:889421766285:android:75fd3d03a6d63151c98cc4',
    messagingSenderId: '889421766285',
    projectId: 'practiceinterview-90a8f',
    storageBucket: 'practiceinterview-90a8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC64fwVdUf7J9GzLlYyRdmwyRuGcYoZws8',
    appId: '1:889421766285:ios:34756ff487666accc98cc4',
    messagingSenderId: '889421766285',
    projectId: 'practiceinterview-90a8f',
    storageBucket: 'practiceinterview-90a8f.firebasestorage.app',
    iosBundleId: 'com.example.kite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC64fwVdUf7J9GzLlYyRdmwyRuGcYoZws8',
    appId: '1:889421766285:ios:34756ff487666accc98cc4',
    messagingSenderId: '889421766285',
    projectId: 'practiceinterview-90a8f',
    storageBucket: 'practiceinterview-90a8f.firebasestorage.app',
    iosBundleId: 'com.example.kite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDztI8Xt-0OS2Mw6_7mGUCmr0JCc1zleTY',
    appId: '1:889421766285:web:8985fe4fdb808b5dc98cc4',
    messagingSenderId: '889421766285',
    projectId: 'practiceinterview-90a8f',
    authDomain: 'practiceinterview-90a8f.firebaseapp.com',
    storageBucket: 'practiceinterview-90a8f.firebasestorage.app',
    measurementId: 'G-PFV3Z98DLZ',
  );
}
